/**
 * The single Tailwind class-merge helper for this application.
 *
 * This module is the target of the `utils` alias in `components.json`
 * (`"utils": "@/lib/utils"`), so every one of the 43 files in
 * `components/ui/` resolves `import { cn } from "@/lib/utils"` to this file —
 * and the 38 generated by `shadcn add` emit that import verbatim. The export
 * name `cn`, its named (non-default) form and its variadic `ClassValue`
 * signature are therefore a fixed contract with the registry, not a local
 * style choice: change any of the three and the generated components stop
 * compiling. There must be exactly one such helper in the tree, which is why
 * this file exists at the aliased path rather than anywhere more convenient.
 *
 * Scope is deliberately one function. General string, date, currency, array
 * and object helpers do NOT belong here — each concern has an owning module
 * (`lib/timezone.ts` for dates, `lib/schema.ts` for validation and slug
 * normalization, `lib/image.ts` for image sizing, `lib/cache-tags.ts` for
 * cache tags). Two exports from the reference implementation this project was
 * pointed at are intentionally absent: `slugify`, because a slug change moves
 * a URL and must go through the `update-slug` command and the route advisory
 * lock rather than being reachable as a free-floating string helper; and
 * `formatPrice`, because nothing here formats a number as currency — the
 * tuition fee schedule migrates as authored strings and a stat value may
 * legitimately read `"5:1"`.
 *
 * Boundary-neutral by design: this module carries neither a client-component
 * directive nor a server-only import guard. Server Components, Client
 * Components and Server Actions all import it, so either marker would break
 * one side — and both are deliberately absent rather than merely unused. It
 * reads no environment (lib/env.ts is the application's sole reader of the
 * process environment) and performs no I/O, which is what keeps it safe to
 * include in a client bundle.
 */

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Combines conditional class values into one deduplicated Tailwind class
 * string.
 *
 * Composition order is load-bearing and runs inside out:
 *
 *   1. `clsx` flattens the arguments — strings, arrays, and objects whose keys
 *      are kept when their value is truthy — and drops every falsy entry, so
 *      the `false && "hidden"`, `null` and `undefined` that conditional markup
 *      produces disappear rather than reaching the DOM as literal text.
 *   2. `twMerge` then resolves conflicts *within* the flattened string, where
 *      the last occurrence of a mutually exclusive utility wins. This is what
 *      lets a caller override a component's own class: `cn("px-2", "px-4")`
 *      yields `"px-4"`, not both. `clsx` alone would emit both and leave the
 *      winner to CSS source order — which for utilities of equal specificity
 *      is decided by stylesheet position, not by call-site order, and so is
 *      not something a caller can control.
 *
 * Every class passed through here is expected to resolve to a design token
 * declared in `app/globals.css` (the `:root` semantic values plus the
 * `@theme inline` alias layer). This function merges class names; it never
 * authors a colour, spacing, radius or size value, and none appears below.
 *
 * @param inputs Class values in precedence order, lowest first. Any falsy
 *   entry is ignored, so callers may pass conditionals inline.
 * @returns The merged class string; `""` when no truthy value was supplied,
 *   never `null` or `undefined`, so the result is always safe to hand
 *   straight to a `className` prop.
 *
 * @example
 * ```ts
 * cn("rounded-md border", isActive && "bg-primary", className)
 * ```
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}

/**
 * Re-exported so call sites can type a `className`-style prop without adding
 * a second direct dependency on `clsx` — most usefully for component props
 * that forward whatever they receive into `cn`.
 *
 * The explicit type-only form is required, not stylistic: `tsconfig.json` sets
 * `isolatedModules: true`, under which a type cannot be re-exported through a
 * value export.
 */
export type { ClassValue };
