/**
 * Button — shadcn/ui registry output, `new-york` style.
 *
 * PROVENANCE. Generated by the pinned CLI, not hand-written:
 *
 *     npx shadcn@4.19.0 add button        # run from `nextjs/`
 *
 * Registry membership was verified BEFORE generating, as §0.3.1 requires
 * ("verified before generation, not assumed"): `npx shadcn@4.19.0 view button`
 * exited 0 and reported `registry/new-york-v4/ui/button.tsx` with exactly one
 * dependency, `radix-ui` — already present in `package.json` at the pinned
 * `1.6.7`, so generation added no manifest entry. The CLI read the committed
 * `components.json` (`style: new-york`, `baseColor: stone`, `rsc: true`,
 * `tsx: true`, `cssVariables: true`, `tailwind.config: ""`, and the
 * `ui` → `@/components/ui` / `utils` → `@/lib/utils` aliases). `new-york` is a
 * deliberate selection for its tighter spacing and smaller default radii, not
 * a CLI default — do not switch it.
 *
 * WHY THIS FILE COMES FIRST. Five files in this directory plus all three
 * authored compositions consume `buttonVariants`; `alert-dialog.tsx` and
 * `calendar.tsx` import the variants factory rather than the component, which
 * is why BOTH symbols are named exports and neither is a default.
 *
 * THE EXEMPTION BOUNDARY (§0.3.5). Unmodified registry output is deliberately
 * scoped OUT of the zero-hardcoded-values rule: `focus-visible:ring-[3px]`,
 * `[&_svg:not([class*='size-'])]:size-4` and `has-[>svg]:px-3` below are
 * arbitrary by design, and rewriting them would defeat the point of pinning the
 * registry and turn the next `shadcn add` into a merge conflict. They are
 * inventoried by `npm run audit:tokens` (which reports them as "Inventoried,
 * NOT failures") rather than corrected. Do not "fix" them. The one axis that
 * does bind generated files is COLOUR, and that is the first deviation below.
 *
 * THREE — AND ONLY THREE — DEVIATIONS FROM THE EMITTED BYTES. Each is forced by
 * a project gate or an explicit project rule that the stock output measurably
 * fails, each was confirmed by RUNNING the gate rather than by reasoning about
 * it, and each is recorded at its call site as well as here so that a future
 * maintainer restoring the registry default reintroduces a known failure rather
 * than discovering one.
 *
 *   1. `destructive` — the emitted class list contains `text-white`.
 *      `scripts/audit-tokens.mjs` classifies this file as generated and fails a
 *      colour literal in generated files too; `white` is in its
 *      `CSS_NAMED_COLOURS` set, which states in terms that `text-white` IS a
 *      violation. Measured before the change:
 *        `x line 14 colourLiteral "text-white" ... audit:tokens FAILED`
 *      Replaced with `text-destructive-foreground`, whose token
 *      `--destructive-foreground: oklch(100% 0 0)` is declared in
 *      `app/globals.css` and aliased in its `@theme inline` block. That value
 *      IS white, so the change is zero-visual-difference and buys the gate:
 *      6.08:1 against `--destructive`, measured in that file.
 *
 *   2. `icon` — the emitted value is `size-9` (36px), a single fixed size.
 *      §0.4.5's responsive matrix requires edit controls and drop targets at
 *      44 x 44px across 320–575px and 32 x 32px above, and 36px is neither
 *      figure. §0.3.3 names the tokens, and `--breakpoint-sm: 576px` puts the
 *      matrix boundary exactly on Tailwind's `sm:` variant, so the contract is
 *      expressible with no custom media query.
 *
 *   3. The base class list opens with `outline-none` in the emitted output, and
 *      that ONE class is deleted. It is not cosmetic: Tailwind compiles it to
 *      `outline-style: none` in `@layer utilities`, which outranks the
 *      project's `:focus-visible { outline: 2px solid var(--color-ring);
 *      outline-offset: 2px }` in `@layer base`. `app/globals.css` states the
 *      rule in terms — "`outline: none` MUST NOT appear anywhere in this
 *      project, with or without `!important`" — because that declaration is the
 *      legacy site's central accessibility defect
 *      (`public/css/style.css:8169`), and `--ring` exists precisely to restore
 *      what it suppressed. Keeping the class would have reproduced the defect
 *      the migration exists to fix.
 *
 *      Measured in headless Chrome BEFORE the deletion: with `:focus-visible`
 *      matching, `outline-style` computed to `none` while `outline-color`
 *      (rgb(0,124,194)), `outline-width` (2px) and `outline-offset` (2px) were
 *      all correct but inert — isolated by removing the class live and watching
 *      the computed style flip to `solid`. The only indicator actually painted
 *      was the component's own 3px `ring-ring/50` box-shadow, sampled at
 *      rgb(125,187,222), which measures **2.00:1** against the page ground and
 *      **2.18:1** against the `--primary` fill — both below WCAG 2.2 SC 1.4.11's
 *      3:1 for a focus indicator. The restored outline measures **4.32:1**
 *      against the page ground, reproducing the figure `globals.css` records.
 *      The two indicators now compose: the box-shadow ring hugs the control and
 *      the offset outline sits clear of it, which is exactly why that file calls
 *      `outline-offset` load-bearing (the same colour is only 1.01:1 against the
 *      green fill, so an unoffset ring would be invisible on a primary button).
 *
 *      Everything else in the base list — including `focus-visible:border-ring`,
 *      `focus-visible:ring-[3px]` and `focus-visible:ring-ring/50` — is
 *      untouched. Removing the suppressor is the minimal fix; re-declaring the
 *      outline here would duplicate the token layer that already owns it.
 *
 * Everything else — the base class list, the six variants, `data-slot`,
 * `data-variant`, `data-size`, the `Slot.Root` switch and the export form — is
 * the emitted output untouched. That includes the `dark:` utilities: one light
 * theme ships and `app/globals.css` carries no `.dark` block, so they are inert
 * (§0.3.3). They are left rather than stripped, and nothing here adds one.
 *
 * THE REGISTRY'S FORMATTING IS ALSO LEFT ALONE, DELIBERATELY. `npx prettier
 * --check` reports this file — and it reports the PRISTINE registry payload
 * identically, verified by checking the unmodified `view` output on its own, so
 * the finding is a property of shadcn output (no semicolons, no trailing
 * commas) rather than of anything above. Do NOT run `prettier --write` here:
 * `prettier-plugin-tailwindcss` would additionally re-sort the class strings,
 * which is exactly the rewrite §0.3.5 refuses because it turns the next
 * `shadcn add` into a conflict. Nothing gates on it — §0.6.6's `lint-types` job
 * runs `tsc --noEmit` and `eslint . --max-warnings=0`, and the CI graph has no
 * formatting job; both of those pass on this file.
 *
 * THE SIZE SCALE IS A SUPERSET OF THE §0.3.2 CONTRACT, AND THAT IS THE FAITHFUL
 * READING. §0.3.2 fixes `size` as `"sm" | "default" | "lg" | "icon"` and
 * forbids narrowing or extending it, while asserting that contract "against the
 * pinned CLI output". The pinned CLI emits eight: those four plus `xs`,
 * `icon-xs`, `icon-sm` and `icon-lg`. All four contract values are present and
 * behave as specified, so the contract holds. The extras are kept because
 * deleting them would BE the hand-narrowing §0.3.2 forbids and would risk a
 * sibling registry component that references one; they are additive and cannot
 * break a consumer. Each still clears WCAG 2.2 SC 2.5.8 (24px, the
 * `--size-target-min` token): `icon-xs` is 24px and `icon-sm` is 32px. The
 * stricter 44px obligation attaches to `size="icon"`, which is what
 * `FieldFrame` renders for the confirm/cancel pair.
 *
 * WHY `asChild` IS LOAD-BEARING RATHER THAN CONVENIENT.
 * `resources/views/layout.antlers.html:54` reads
 * `<a href="/donate" style="margin-left: -5px;"><button>Donate Now</button></a>`
 * — an interactive element nested inside another, which is invalid HTML and
 * produced TWO tab stops for one action. It was also the only `<button>` in the
 * entire rendered legacy site, and the only element anywhere that kept a focus
 * ring, purely because Chrome's UA stylesheet reached it where
 * `public/css/style.css:8169`'s `outline: none !important` on `a:hover, a:focus`
 * did not. The port renders ONE element carrying both roles:
 *
 *     <Button asChild><Link href="/donate">Donate Now</Link></Button>
 *
 * Never nest an interactive element inside another to get link behaviour.
 *
 * FOCUS AND COLOUR COME FROM THE TOKEN LAYER, NOT FROM HERE. The ring resolves
 * through `--ring`, which aliases `--secondary` and is the token that repairs
 * the suppression above; `app/globals.css` additionally applies a global
 * `:focus-visible { outline: 2px solid var(--color-ring); outline-offset: 2px }`
 * whose offset is load-bearing, because the ring measures only 1.01:1 against
 * the `--primary` fill and the offset is what lifts it onto the page ground.
 * `--primary` is the DARKENED green `oklch(55% 0.162 140.6)` (#30871d, 4.56:1)
 * and `--secondary` the darkened blue `oklch(56.4% 0.142 243.2)` (#007cc2,
 * 4.54:1) — the legacy `$band5` and `$blue` measured 3.51:1 and 3.21:1 and both
 * failed AA. The legacy 30px pill radius survives as `--radius-pill`, applied by
 * the call sites that want the legacy CTA look rather than imposed on every
 * button here.
 *
 * ACCESSIBLE NAMING IS THE CALLER'S OBLIGATION AND IT IS NOT OPTIONAL. An
 * icon-only button carries no text node, so it MUST receive either an
 * `aria-label` or visually-hidden text:
 *
 *     <Button size="icon" aria-label="Confirm change"><Check /></Button>
 *
 * `lighthouserc.json` asserts Lighthouse Accessibility at exactly 1.00, and the
 * legacy site failed `link-name` three times over — the nav toggle plus both
 * icon-only social links, each with an empty accessible name. Icons come from
 * `lucide-react` as NAMED imports only, never a namespace import, so
 * tree-shaking holds (§0.6.5).
 *
 * No `"use client"` directive, exactly as emitted: this component holds no
 * state and no effect, so it renders in a Server Component. A caller passing
 * `onClick` supplies the client boundary itself.
 */

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  // DEVIATION 3 of 3. The emitted base list opens with `outline-none`, which is
  // deleted here — and ONLY that one class is deleted. See the header: it
  // compiles into `@layer utilities`, outranking the project's
  // `:focus-visible { outline: 2px solid var(--color-ring); outline-offset: 2px }`
  // in `@layer base`, so the ring this migration exists to restore never
  // painted. Measured in headless Chrome before the deletion:
  // `outline-style: none` while `:focus-visible` matched. Do not restore it.
  "inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        // DEVIATION 1 of 3. `text-destructive-foreground` replaces the emitted
        // `text-white`: same rendered colour (the token is `oklch(100% 0 0)`),
        // but `npm run audit:tokens` fails the bare named colour `white` in
        // generated files. Do not restore `text-white`.
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:bg-destructive/60 dark:focus-visible:ring-destructive/40",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        xs: "h-6 gap-1 rounded-md px-2 text-xs has-[>svg]:px-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        // DEVIATION 2 of 3. The emitted value is `size-9` — a fixed 36px, which
        // is neither figure in §0.4.5's matrix for edit controls and drop
        // targets (44 x 44px at 320–575px, 32 x 32px above). Mobile-first: the
        // base declaration is the touch size and `sm:` steps down to the
        // pointer size, `--breakpoint-sm` being 576px so the variant lands
        // exactly on the matrix boundary. Both values are §0.3.3 tokens read
        // through Tailwind's custom-property shorthand, because `--size-*` is
        // not a Tailwind namespace and so generates no utility of its own.
        // This is the size `FieldFrame` renders for confirm/cancel on every
        // editable field, so a regression here is a regression in the
        // migration's primary feature.
        icon: "size-(--size-control-touch) sm:size-(--size-control)",
        "icon-xs": "size-6 rounded-md [&_svg:not([class*='size-'])]:size-3",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
