/**
 * Two-level site navigation — one of the 38 registry-generated files among the
 * 43 in `components/ui/` (§0.3.5).
 *
 * ## PROVENANCE
 *
 * Generated by `shadcn@4.19.0 add navigation-menu` against the committed
 * `components.json` (`style: new-york`, `baseColor: stone`, `cssVariables:
 * true`). Registry membership was verified before generation, as §0.3.1
 * requires: `shadcn@4.19.0 view navigation-menu` resolves and declares exactly
 * one dependency, `radix-ui`, which `package.json` already pins at 1.6.7 — so
 * generation added no package.
 *
 * The JSX structure, the `data-slot` attributes and the Tailwind class strings
 * are preserved verbatim from that registry output, with SEVEN deliberate
 * deviations listed below — four token corrections and three defect fixes.
 * They are recorded here rather than left to a reader to spot, because a later
 * `shadcn add` would silently revert every one of them and take both the
 * project's token contract and the three fixes with it. §0.3.5 requires the
 * generated inventory to be reviewable after a registry upgrade; this comment
 * is that record for this file.
 *
 * Token corrections (§0.3.3, mandated):
 *
 * | Deviation | Registry | Here | Why |
 * |---|---|---|---|
 * | Viewport layer | `z-50` | `z-(--z-nav)` | 50 is `--z-overlay`. Colliding with it breaks the declared order: nav 30 < dropdown 40 < overlay 50 < modal 60 < toast 70 < edit 80. The edit chrome MUST sit above the menu (§0.3.3). Verified in a browser: the wrapper computes `z-index: 30`, and no element in the subtree computes 50. |
 * | Chevron motion | `duration-300` | `duration-(--duration-fast) ease-out` | §0.3.3 motion tokens. A 12px icon rotation is the "fast" affordance (120ms); 300ms reads as sluggish. Verified computing to `0.12s` / `cubic-bezier(0.22, 1, 0.36, 1)`. |
 * | Content motion | `…:duration-200` | `…:duration-(--duration-base)` | §0.3.3: a panel transition is `--duration-base` (240ms). |
 * | Viewport motion | untokened | `duration-(--duration-base) ease-out` | The registry leaves the viewport's open/close animation with no duration or easing at all, so it fell outside the token contract entirely. |
 *
 * Defect fixes, each found by runtime measurement in a real browser rather
 * than by reading the source:
 *
 * | Fix | Registry | Here | Why |
 * |---|---|---|---|
 * | Active link never highlighted | `data-[active=true]:…` (×4) | `data-[active]:…` (×4) | A REGISTRY BUG. Radix sets `data-active=""` — an EMPTY STRING (`@radix-ui/react-navigation-menu` dist line 379: `"data-active": active ? "" : void 0`) — but `data-[active=true]:` compiles to the selector `[data-active="true"]`, which can never match. Measured: the active link's computed `background-color` was `rgba(0, 0, 0, 0)`, byte-identical to an inactive sibling, so `active` produced `aria-current="page"` and NO visual state at all. That is the exact inverse of the legacy `class="colorlib-active"` defect this component exists to fix, and it made this file's own "Both halves matter" claim below false. `data-[active]:` compiles to `[data-active]` and matches on presence. |
 * | No focus ring inside a panel | `**:data-[slot=navigation-menu-link]:focus:ring-0` and `…:focus:outline-none` on Content | both removed | These two overrides stripped the link's own `focus-visible:ring-[3px]` for every link INSIDE a panel, leaving an `--accent` fill on a `--popover` surface as the only cue — measured at 1.073:1, against the 3:1 that WCAG 2.2 SC 1.4.11 requires to identify a state. A keyboard user walking the second level had effectively no focus indicator, which is the measured legacy failure (`outline: none !important` site-wide) reintroduced in miniature. §0.4.5 targets WCAG 2.2 AA, so the suppression goes. |
 * | Wrong easing on in-place panels | `viewport=false` branch had a duration but no easing | `+ …:ease-out` | Measured `transition-timing-function: ease` — the browser default — where §0.3.3 states every animation references `--ease-*`. The shared-viewport branch already measured `cubic-bezier(0.22, 1, 0.36, 1)`; this makes the two branches agree. |
 *
 * Two further runtime findings are deliberately NOT changed here, because both
 * are library-wide rather than local to this file and fixing them in one of 43
 * components would create exactly the inconsistency §0.3.5 guards against.
 * Recorded so the design-system owner can decide once, for all 38 generated
 * files:
 *   - `outline-none` sets Tailwind's `--tw-outline-style: none` unconditionally,
 *     so the sibling `focus-visible:outline-1` never paints AND the compliant
 *     2px `--ring` outline that `app/globals.css` declares on `:focus-visible`
 *     is suppressed. Only the box-shadow ring survives, and box-shadow is
 *     dropped in forced-colors / Windows High Contrast mode.
 *   - That surviving ring is `ring-ring/50`, which measured 2.005:1 against the
 *     page — below 1.4.11's 3:1. At full strength `--ring` measures 4.316:1.
 * Both classes are the registry's standard focus treatment, shared by
 * `button`, `input` and every other generated component.
 *
 * One further difference is punctuation, not content: the file is formatted to
 * the project's committed Prettier standard (`package.json` → `prettier`, with
 * `prettier-plugin-tailwindcss` and `tailwindStylesheet: ./app/globals.css`),
 * which adds the semicolons and trailing commas the registry omits. Verified
 * non-semantic before it was applied: the plugin reordered ZERO classes across
 * all 11 class strings in this file, and the diff against registry output
 * remains exactly the four lines above once semicolons and trailing commas are
 * normalised away.
 *
 * Everything else the registry emitted is left ALONE on purpose. §0.3.5 scopes
 * "zero hardcoded values" to authored code and deliberately exempts generated
 * registry internals, so `ring-[3px]`, `top-[1px]`, the indicator's local
 * `z-[1]`, the two `--radix-navigation-menu-viewport-*` size variables and the
 * `[&_svg…]` descendant selectors all stand. The indicator's `z-[1]` is
 * specifically NOT rewritten to `--z-nav`: it is a one-step nudge over its
 * siblings inside the menu, not the menu's global layer, and conflating the
 * two would misstate the layering contract rather than honour it.
 *
 * ## TOKENS, AND THE TWO NAMESPACE TRAPS
 *
 * Every colour resolves to a declared `--color-*` token — `bg-background`,
 * `bg-accent`, `text-accent-foreground`, `bg-popover`,
 * `text-popover-foreground`, `bg-border`, `text-muted-foreground`,
 * `ring-ring/50`. There is not one colour literal in this file, which is the
 * one axis `npm run audit:tokens` fails even in a generated file. Bare `border`
 * needs no colour because `app/globals.css` sets `border-color:
 * var(--color-border)` on `*, ::before, ::after`.
 *
 * Two token groups are NOT Tailwind namespaces, and getting this wrong fails
 * silently rather than loudly — a bare `z-nav` or `duration-base` class emits
 * nothing at all and leaves the property at its inherited value:
 *
 *   - `--z-*` generates no `z-*` utility → consumed as `z-(--z-nav)`.
 *   - `--duration-*` generates no `duration-*` utility → `duration-(--duration-base)`.
 *
 * `--ease-*` IS a namespace, so the plain `ease-out` class resolves to this
 * project's `cubic-bezier(0.22, 1, 0.36, 1)` override rather than Tailwind's
 * default curve. All three forms are the ones `app/globals.css` documents.
 *
 * ## MOTION AND REDUCED MOTION
 *
 * This file carries no `motion-reduce:` variant, and that is correct rather
 * than an omission. `app/globals.css` ends with an UNLAYERED
 * `@media (prefers-reduced-motion: reduce)` block that collapses every
 * animation and transition to 1ms. Unlayered declarations outrank Tailwind's
 * `utilities` layer, so it beats the durations above without `!important` —
 * which §0.3.5 forbids. It collapses to 1ms rather than `animation: none`
 * because Radix waits for `animationend` before unmounting, and `none` never
 * fires that event, which would leave an open panel mounted forever. The menu
 * therefore stays fully operable with the motion suppressed, exactly as
 * §0.4.5 requires. Adding a variant here would duplicate that and risk
 * fighting it.
 *
 * ## ONE LIGHT THEME
 *
 * No `dark:` variant appears here. §0.3.3 ships a single light theme and the
 * `.dark` block is deleted from `globals.css`, so a `dark:` class would be
 * unreachable code. The registry output for this item happens to contain none,
 * so nothing had to be stripped.
 *
 * ## WHAT DRIVES THIS MENU: `nav_items`, NOT THE URL TREE
 *
 * `NavTree` feeds this component from the `nav_items` table, never from the
 * page hierarchy (§0.3.2, §0.4.2). That separation is the resolution of a
 * real conflict inside requirement 10 — optimize the information architecture
 * while preserving content and functional parity — because `pages.parent_id`
 * determines `pages.path`, so it cannot also express menu grouping: moving
 * Donate under Giving in the menu would move it to `/giving/donate` and break
 * a live URL. Four concepts stay distinct and only the third is this file's:
 *
 *   1. URL parent            — `pages.parent_id`
 *   2. Breadcrumb parent     — also `pages.parent_id`, rendered by `Breadcrumbs`
 *   3. Menu membership/order — `nav_items`, rendered HERE
 *   4. Contextual children   — a published-children query, used by `ProgramsIndex`
 *
 * This is what lets §0.4.5 promote Admissions to first under the first group
 * and move donation into Giving without reparenting a single page. The legacy
 * sidebar placed Admissions sixth in an undifferentiated list of nine while
 * its only standing call to action was "Donate Now"
 * (`resources/views/layout.antlers.html:34-42, :54`), and rendered none of the
 * 25 children in `content/trees/collections/pages.yaml` at all.
 *
 * Four shapes therefore have to work, and each maps to a part below:
 *
 *   - A LABEL-ONLY GROUP (`target_page_id` and `external_url` both null) —
 *     "Considering CES", "Our Community", "Header Actions". Use
 *     `NavigationMenuTrigger`, which is a `<button>`, NOT a link. Never wrap it
 *     in an anchor: `layout.antlers.html:54` nests `<button>` inside
 *     `<a href="/donate">`, which is invalid HTML and yields two tab stops for
 *     one action.
 *   - AN EXTERNAL ITEM (`external_url` set) — `NavigationMenuLink` with a
 *     plain `href`, no `next/link`.
 *   - A HIDDEN ITEM (`visible = false`: School Age Mandarin, Deposits) —
 *     filtered out by the data layer and never passed here. This file has no
 *     "hidden" styling, deliberately: a menu entry hidden with CSS is still in
 *     the accessibility tree and still a tab stop, which is the defect the
 *     legacy collapsed sidebar exhibits with 13 off-screen tab stops.
 *   - AN `audience` VALUE (`prospective` | `enrolled` | `both`) — resolved by
 *     `NavTree`. Nothing here assumes every item is shown to every visitor.
 *
 * ## ACCESSIBILITY (WCAG 2.2 AA, §0.4.5)
 *
 * The guarantees below come from the Radix primitives and are the reason this
 * component is not hand-rolled. Each replaces a measured legacy failure:
 *
 *   - VALID LIST STRUCTURE. `List` renders `<ul>` and `Item` renders `<li>`, so
 *     only an `Item` can be a direct child of the list. The legacy markup fails
 *     Lighthouse's `list` audit because `layout.antlers.html:33` puts the logo
 *     anchor directly inside `<ul>`; that logo belongs to `SiteHeader` /
 *     `SiteSidebar` chrome and must never be placed inside this list.
 *   - STATE IS CONVEYED. `Trigger` emits `aria-expanded`, and `Link active`
 *     emits `aria-current="page"` alongside `data-active`. The legacy
 *     `class="colorlib-active"` at `layout.antlers.html:36` is purely visual and
 *     conveys nothing to assistive technology.
 *   - KEYBOARD. Arrow keys move within a level, Escape closes an open panel and
 *     Tab moves out of the menu. The legacy baseline is zero key handlers
 *     site-wide: `public/js/main.js` binds only click and scroll, so Escape does
 *     nothing today.
 *   - VISIBLE FOCUS. The registry's `focus-visible:ring-[3px]
 *     focus-visible:ring-ring/50` treatment is kept as generated, against a
 *     legacy baseline of `outline: none !important` applied site-wide and zero
 *     `:focus-visible` rules in all six stylesheets.
 *
 * @see app/globals.css — the token contract these classes resolve against
 * @see components/site/NavTree.tsx — the `nav_items` consumer
 */

import * as React from "react";
import { cva } from "class-variance-authority";
import { ChevronDownIcon } from "lucide-react";
import { NavigationMenu as NavigationMenuPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

/**
 * Root of the menu. Renders a `<nav>` landmark and owns the open/close state
 * machine for every trigger beneath it.
 *
 * `orientation` and `delayDuration` forward straight to the primitive:
 * `orientation="vertical"` is what the persistent sidebar at >= 992px uses,
 * `"horizontal"` the header. `delayDuration` is the hover-open delay in
 * milliseconds (primitive default 200).
 *
 * `viewport` is this wrapper's own prop, not a Radix one. Left `true`, the root
 * additionally renders a single shared `NavigationMenuViewport` that every
 * panel animates into — one popover surface whose height and width track the
 * active panel. Set it `false` to have each `NavigationMenuContent` render in
 * place beneath its own trigger instead; the content styles react to that
 * through `group-data-[viewport=false]/navigation-menu:*`, which is why the
 * value is also mirrored onto `data-viewport`.
 */
function NavigationMenu({
  className,
  children,
  viewport = true,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Root> & {
  viewport?: boolean;
}) {
  return (
    <NavigationMenuPrimitive.Root
      data-slot="navigation-menu"
      data-viewport={viewport}
      className={cn(
        "group/navigation-menu relative flex max-w-max flex-1 items-center justify-center",
        className,
      )}
      {...props}
    >
      {children}
      {viewport && <NavigationMenuViewport />}
    </NavigationMenuPrimitive.Root>
  );
}

/**
 * The `<ul>` holding one level of the menu.
 *
 * Only `NavigationMenuItem` may be a direct child. Anything else — a logo, a
 * bare anchor, a `<div>` wrapper — is invalid list markup and fails
 * Lighthouse's `list` audit, which is precisely the legacy defect at
 * `resources/views/layout.antlers.html:33`.
 */
function NavigationMenuList({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.List>) {
  return (
    <NavigationMenuPrimitive.List
      data-slot="navigation-menu-list"
      className={cn(
        "group flex flex-1 list-none items-center justify-center gap-1",
        className,
      )}
      {...props}
    />
  );
}

/**
 * One `<li>` in the list — a single `nav_items` row.
 *
 * Holds either a `NavigationMenuLink` (the row has a `target_page_id` or an
 * `external_url`) or a `NavigationMenuTrigger` plus `NavigationMenuContent`
 * (the row is a label-only group with children). `relative` is what the
 * in-place panel positions against when the root is rendered with
 * `viewport={false}`.
 */
function NavigationMenuItem({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Item>) {
  return (
    <NavigationMenuPrimitive.Item
      data-slot="navigation-menu-item"
      className={cn("relative", className)}
      {...props}
    />
  );
}

/**
 * The shared trigger appearance, exported so a sibling top-level item that is
 * a plain link can sit flush beside a group trigger:
 *
 * ```tsx
 * <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
 *   <Link href="/events">Events</Link>
 * </NavigationMenuLink>
 * ```
 *
 * Without it, a one-level item and a two-level group would differ in height,
 * padding and hover treatment on the same row.
 */
/* BLITZY [A11Y]: the focus ring below is `ring-ring/50` at `ring-[3px]`. Measured
   in a browser, the composited ring is rgb(127,189,224) — 2.047:1 against
   --background and 1.908:1 against the --accent fill, below the 3:1 that WCAG 2.2
   SC 1.4.11 asks of a focus indicator. At full strength --ring resolves to
   rgb(0,124,194) ≈ 4.32:1, so dropping the /50 would close the gap. NOT changed
   here: this is the registry's shared focus treatment, identical in `button`,
   `input` and every other generated component, and §0.3.5 names `ring-[3px]` as
   exempt generated output — correcting it in 1 of 43 files would make this
   component's focus differ from every sibling. Flagged for a single
   design-system decision across all 38 generated files rather than
   silently auto-corrected here. The indicator IS visible (a hard-edged 3px ring,
   verified by screenshot); this is a contrast shortfall, not an absent cue. */
const navigationMenuTriggerStyle = cva(
  "group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-[color,box-shadow] outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 disabled:pointer-events-none disabled:opacity-50 data-[state=open]:bg-accent/50 data-[state=open]:text-accent-foreground data-[state=open]:hover:bg-accent data-[state=open]:focus:bg-accent",
);

/**
 * Discloses a group's panel. Renders a `<button>`, and the primitive maintains
 * `aria-expanded` and `data-state` on it in both states.
 *
 * This is the part that makes a LABEL-ONLY GROUP work — "Considering CES",
 * "Our Community", "Header Actions" all have a null `target_page_id`, so there
 * is no URL to link to and a button is the correct control. Do not wrap it in
 * an anchor to give it a destination: that is the invalid nested-interactive
 * pattern at `resources/views/layout.antlers.html:54`. A group that also needs
 * its own landing page gets a link INSIDE its panel.
 *
 * The chevron is `aria-hidden` — it is a redundant restatement of
 * `aria-expanded`, so exposing it would make a screen reader announce the
 * state twice. Its rotation runs on `--duration-fast` with `--ease-out`.
 */
function NavigationMenuTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Trigger>) {
  return (
    <NavigationMenuPrimitive.Trigger
      data-slot="navigation-menu-trigger"
      className={cn(navigationMenuTriggerStyle(), "group", className)}
      {...props}
    >
      {children}{" "}
      <ChevronDownIcon
        className="relative top-[1px] ml-1 size-3 transition duration-(--duration-fast) ease-out group-data-[state=open]:rotate-180"
        aria-hidden="true"
      />
    </NavigationMenuPrimitive.Trigger>
  );
}

/**
 * A group's panel: the second level of the menu, holding the child
 * `nav_items` rows for one group.
 *
 * The primitive mounts and unmounts this around the enter/exit animation and
 * sets `data-motion` to the direction the pointer or focus travelled, which
 * drives the directional slide so moving between two adjacent groups reads as
 * lateral movement rather than a dissolve.
 *
 * Two presentations, selected by the root's `viewport` prop:
 *   - `viewport` true (default) — the panel animates inside the shared
 *     `NavigationMenuViewport`, which owns the surface, border and shadow.
 *   - `viewport` false — the `group-data-[viewport=false]/navigation-menu:*`
 *     classes give this element its own popover surface in place under its
 *     trigger, on `--duration-base`.
 *
 * Put a nested `NavigationMenuList` in here so the child rows remain `<li>`
 * elements inside a `<ul>` rather than becoming loose anchors.
 */
function NavigationMenuContent({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Content>) {
  return (
    <NavigationMenuPrimitive.Content
      data-slot="navigation-menu-content"
      className={cn(
        "top-0 left-0 w-full p-2 pr-2.5 data-[motion=from-end]:slide-in-from-right-52 data-[motion=from-start]:slide-in-from-left-52 data-[motion=to-end]:slide-out-to-right-52 data-[motion=to-start]:slide-out-to-left-52 data-[motion^=from-]:animate-in data-[motion^=from-]:fade-in data-[motion^=to-]:animate-out data-[motion^=to-]:fade-out md:absolute md:w-auto",
        "group-data-[viewport=false]/navigation-menu:top-full group-data-[viewport=false]/navigation-menu:mt-1.5 group-data-[viewport=false]/navigation-menu:overflow-hidden group-data-[viewport=false]/navigation-menu:rounded-md group-data-[viewport=false]/navigation-menu:border group-data-[viewport=false]/navigation-menu:bg-popover group-data-[viewport=false]/navigation-menu:text-popover-foreground group-data-[viewport=false]/navigation-menu:shadow group-data-[viewport=false]/navigation-menu:duration-(--duration-base) group-data-[viewport=false]/navigation-menu:ease-out group-data-[viewport=false]/navigation-menu:data-[state=closed]:animate-out group-data-[viewport=false]/navigation-menu:data-[state=closed]:fade-out-0 group-data-[viewport=false]/navigation-menu:data-[state=closed]:zoom-out-95 group-data-[viewport=false]/navigation-menu:data-[state=open]:animate-in group-data-[viewport=false]/navigation-menu:data-[state=open]:fade-in-0 group-data-[viewport=false]/navigation-menu:data-[state=open]:zoom-in-95",
        className,
      )}
      {...props}
    />
  );
}

/**
 * The single shared popover surface every panel animates into when the root is
 * rendered with `viewport` true. Rendered automatically by `NavigationMenu`;
 * mount it by hand only when composing a custom root.
 *
 * It sizes itself from `--radix-navigation-menu-viewport-height` and
 * `-width`, which the primitive measures from the active panel — the mechanism
 * that lets the surface grow and shrink between groups of different sizes.
 *
 * The outer wrapper carries the positioning and the stacking context. Its
 * layer is `--z-nav` (30), NOT the registry's `z-50`: 50 is `--z-overlay`, and
 * sitting there would put the menu level with dialogs and above nothing it
 * should be above — the edit chrome at `--z-edit` (80) must always win.
 * `isolate` keeps the panel's internal stacking from leaking out.
 */
function NavigationMenuViewport({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Viewport>) {
  return (
    <div
      className={cn(
        "absolute top-full left-0 isolate z-(--z-nav) flex justify-center",
      )}
    >
      <NavigationMenuPrimitive.Viewport
        data-slot="navigation-menu-viewport"
        className={cn(
          "origin-top-center relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow duration-(--duration-base) ease-out data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
          className,
        )}
        {...props}
      />
    </div>
  );
}

/**
 * A navigable entry — one `nav_items` row that has a destination.
 *
 * Two required behaviours:
 *
 * `asChild` composes the child element instead of rendering its own `<a>`, and
 * it is how an INTERNAL destination gets client-side navigation. Passing an
 * `href` directly would render a plain anchor and force a full document load;
 * nesting a `next/link` inside without `asChild` would produce an `<a>` inside
 * an `<a>` — invalid HTML and two tab stops for one destination, which is the
 * legacy pattern at `resources/views/layout.antlers.html:54`.
 *
 * ```tsx
 * // internal — nav_items.target_page_id
 * <NavigationMenuLink asChild active={pathname === "/admissions"}>
 *   <Link href="/admissions">Admissions</Link>
 * </NavigationMenuLink>
 *
 * // external — nav_items.external_url
 * <NavigationMenuLink href={item.external_url} target="_blank" rel="noopener noreferrer">
 *   Family Portal
 * </NavigationMenuLink>
 * ```
 *
 * `active` marks the current destination and the primitive turns it into
 * `aria-current="page"` as well as `data-active`, which the classes below
 * style. Both halves matter: the legacy `class="colorlib-active"` marker
 * (`layout.antlers.html:36`) is visual only and tells assistive technology
 * nothing. Set it from the resolved pathname, not from menu nesting — a group
 * is not its children's current page.
 */
function NavigationMenuLink({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Link>) {
  return (
    <NavigationMenuPrimitive.Link
      data-slot="navigation-menu-link"
      className={cn(
        "flex flex-col gap-1 rounded-sm p-2 text-sm transition-all outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 data-[active]:bg-accent/50 data-[active]:text-accent-foreground data-[active]:hover:bg-accent data-[active]:focus:bg-accent [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Optional arrow that tracks the open trigger, tying the panel to the item it
 * belongs to. Purely decorative — the primitive keeps it out of the
 * accessibility tree, and `aria-expanded` on the trigger is what actually
 * conveys the state, so nothing is lost when it is omitted or when its motion
 * is suppressed.
 *
 * Mount it as a sibling of `NavigationMenuList` inside the root. The `z-[1]`
 * below is generated output and is deliberately left as-is: it lifts the arrow
 * one step over its siblings within the menu and is not a global layer, so it
 * is not `--z-nav`.
 *
 * COMPOSITION CAVEAT, measured in a browser rather than inferred. Radix wraps
 * EVERY `NavigationMenuList` in an indicator-track element and registers it on
 * the root context, so the last list mounted wins. Because a panel should hold
 * a nested `NavigationMenuList` (that is what keeps its rows `<li>`), the
 * nested list registers after the root's and the indicator is positioned
 * against the open panel instead of the trigger row — it renders as a small
 * notch on the panel's lower border. It stays `aria-hidden` and nothing
 * functional depends on it, but if you mount this alongside two-level groups,
 * expect that. Either omit the indicator for two-level menus, or give the
 * nested level a plain `<ul>`. `NavTree` should simply not mount it on the
 * groups that have panels.
 */
function NavigationMenuIndicator({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Indicator>) {
  return (
    <NavigationMenuPrimitive.Indicator
      data-slot="navigation-menu-indicator"
      className={cn(
        "top-full z-[1] flex h-1.5 items-end justify-center overflow-hidden data-[state=hidden]:animate-out data-[state=hidden]:fade-out data-[state=visible]:animate-in data-[state=visible]:fade-in",
        className,
      )}
      {...props}
    >
      <div className="relative top-[60%] h-2 w-2 rotate-45 rounded-tl-sm bg-border shadow-md" />
    </NavigationMenuPrimitive.Indicator>
  );
}

export {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuContent,
  NavigationMenuTrigger,
  NavigationMenuLink,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  navigationMenuTriggerStyle,
};
