/**
 * Popover — the anchored overlay surface.
 *
 * One of the 38 registry-generated files among the 43 in `components/ui/`
 * (§0.3.5). Generated by `shadcn add popover` against the pinned CLI at
 * 4.19.0 and the committed `components.json`, after `shadcn view popover`
 * confirmed registry membership as §0.3.1 requires. The item resolved and
 * declared exactly one dependency, `radix-ui`, which is already pinned at
 * 1.6.7 in `package.json` — so generation added nothing to the manifest.
 *
 * The pinned registry emits SEVEN parts, three more than a reader of §0.3.2's
 * component table would expect: `PopoverHeader`, `PopoverTitle` and
 * `PopoverDescription` accompany `Popover`, `PopoverTrigger`,
 * `PopoverContent` and `PopoverAnchor`. All seven are exported unchanged
 * because §0.3.1 fixes the rule for a resolving item — it is generated as the
 * CLI reports it, not trimmed to a subset someone anticipated.
 *
 * WHY THIS FILE AND NOT `dialog.tsx`
 *
 * This is the component that owns positioning. §0.3.2's "Anchored overlays and
 * edit affordances" row states it directly: `side`, `align`, `sideOffset` and
 * `alignOffset` live here, and `PopoverContent`, `TooltipContent` and
 * `DropdownMenuContent` all forward them to Radix's positioner. The pinned
 * `dialog.tsx` is centered and exposes none of them. A consumer reaching for a
 * positioning prop on a dialog has chosen the wrong component, not the wrong
 * prop — which is precisely why the authored `date-picker.tsx` composes this
 * file with `Calendar` and `Button` rather than composing a dialog.
 *
 * Two known consumers, both of which depend on the forwarding above:
 *
 *   - `components/ui/date-picker.tsx` (authored, §0.3.4) anchors a calendar to
 *     its trigger. Its public API is an ISO `yyyy-MM-dd` string and never a
 *     `Date`, because `events.event_date` is a zone-free Postgres `date` and a
 *     `Date` would let the browser's own zone shift the day. Nothing about
 *     that value shaping belongs in this file, and deliberately nothing here
 *     offers a convenience that would tempt a consumer to bypass it: this
 *     component transports layout, not values.
 *   - `components/cms/FocalPointPicker.tsx` overlays a draggable crosshair on
 *     an image at its rendered aspect ratio and writes x, y and zoom through
 *     the `update-focal-point` command. It needs a surface that tracks one
 *     specific element, which is what `sideOffset` and collision handling are
 *     for.
 *
 * TOKEN CONTRACT (§0.3.3, §0.3.5)
 *
 * §0.3.5 exempts unmodified registry internals from the arbitrary-value ban on
 * purpose — rewriting `w-72`, `p-4` or `outline-hidden` would make the next
 * `shadcn add` a merge conflict for no benefit — but the exemption covers the
 * SIZING axis only. Colour never, and the two values §0.3.5's Phase-5 rules
 * name for this file never. So exactly two of the generated classes are
 * corrected below and every other one is verbatim:
 *
 *   1. The registry's fixed `z-index: 50` becomes `z-(--z-dropdown)`. §0.3.3
 *      assigns anchored overlays `--z-dropdown: 40`, beneath `--z-overlay: 50`
 *      and `--z-modal: 60` and well beneath `--z-edit: 80`, because the edit
 *      chrome must sit above every public overlay. The generated value is not
 *      merely untokenized, it is the wrong layer — it would tie an anchored
 *      panel with the modal overlay and let it cover the edit toolbar. The
 *      `z-(…)` spelling is required rather than stylistic: Tailwind 4 has no
 *      `--z-*` namespace, so `z-dropdown` would generate no utility at all.
 *      `app/globals.css` declares the prescribed consumer form on the token
 *      itself, and declares these tokens in `@theme static` so they survive
 *      unused rather than being tree-shaken into an undefined variable.
 *   2. The registry's default medium shadow becomes `shadow-popover`,
 *      resolving elevation to `--shadow-popover: 0 4px 16px
 *      oklch(36% 0.022 140 / .10)`. Worth stating because the failure would
 *      have been silent: `app/globals.css` resets no namespace, so Tailwind's
 *      default `--shadow-md` still resolves, and the generated class would
 *      have rendered a plausible shadow while bypassing the token contract
 *      entirely.
 *
 * Both corrections are described above without writing the two superseded
 * class names literally, and that is deliberate rather than coy. Tailwind's
 * scanner extracts candidates from whole files, comments included, so naming
 * them here would emit their rules into the production bundle — dead weight
 * against §0.9.3's CSS budget, and misleading besides, since a reviewer
 * grepping the compiled stylesheet would find the very z-index layer this
 * component was corrected away from. Verified by compiling `app/globals.css`
 * with this file as the only scanned source: the emitted set contains
 * `.z-(--z-dropdown)` and `.shadow-popover` and neither superseded rule.
 * Please keep it that way if you edit this block.
 *
 * ONE ADDED CLASS: `max-w-(--radix-popover-content-available-width)`
 *
 * This is not a preference. Browser measurement at the 320px floor showed the
 * registry's bare `w-72` clipping the panel off-screen: with a trigger flush to
 * the right edge, `side="right"` correctly flipped to `left` and landed at
 * `left: -92px` — 92px of a 288px panel, and part of a focused button, off the
 * screen and unreachable, since a portalled `position: fixed` wrapper adds no
 * scrollable overflow. The mirror case clipped 80px off the right. Radix was
 * not at fault: it published the true space on the wrapper
 * (`--radix-popover-content-available-width` of 195.58px and 208.47px
 * respectively) and the panel simply never read it. Nor could collision
 * handling rescue it — for a left/right placement `shift` works on the cross
 * axis only, so once `flip` has chosen a horizontal side nothing pulls the
 * panel back horizontally, and 288px plus a 4px offset cannot fit beside any
 * tappable trigger in 320px. Every `side="left"`/`side="right"` popover was
 * therefore guaranteed to clip at the narrowest supported width, which §0.4.5
 * forbids outright.
 *
 * Consuming the variable Radix already publishes is the design system's own
 * idiom rather than a local invention: the pinned registry's `select` and
 * `dropdown-menu` both constrain themselves the same way, with
 * `max-h-(--radix-select-content-available-height)` and
 * `max-h-(--radix-dropdown-menu-content-available-height)`. The namespaced
 * spelling matches the `origin-(--radix-popover-content-transform-origin)`
 * already in the same class string. `w-72` is untouched, so nothing changes
 * wherever there is room — the constraint binds only when the panel would
 * otherwise leave the viewport.
 *
 * A matching `max-h-(…-available-height)` is deliberately NOT added. No
 * measured case failed vertically — `flip` handled every one, including a
 * trigger 12px below the sticky header — and a height cap without an overflow
 * strategy would silently truncate content instead of moving it, which is the
 * worse failure. If a tall panel ever needs it, add the cap and a scroll
 * container together.
 *
 * After the fix, re-measurement showed the panel shrinking to exactly the
 * published width (288px to 195.58px and 208.47px in the two failing cases)
 * and holding exactly 288px everywhere there was room — at 320px and at
 * desktop alike. One sub-pixel residue remains and is recorded here so it is
 * not later misread as unfixed clipping: Radix writes the positioner's
 * translate in whole pixels while deriving available-width from the unrounded
 * position, so a panel can end up to half a pixel past the viewport — 0.47px
 * was measured, exactly equal to that rounding shift, and the same artefact
 * shows on the vertical axis as an 11.81px gap for a requested 12px offset.
 * It costs a fraction of the panel's own border, creates no scroll region and
 * clips no glyph, corner or control, so it is left alone: shaving a pixel off
 * every constrained panel to chase it would be a real visual cost for no
 * user-visible gain, and the rounding belongs to the primitive.
 *
 * TWO THINGS THIS COMPONENT DOES NOT DO FOR YOU
 *
 * 1. It does not name the panel. Radix gives the content `role="dialog"`, and
 *    a dialog with no accessible name is announced as an unnamed dialog; axe
 *    reports `aria-dialog-name` (serious, best-practice) against it. The
 *    registry does not wire `PopoverTitle` to the content automatically and
 *    this file deliberately does not either, because a generated
 *    `aria-labelledby` pointing at an id no consumer rendered would be a
 *    genuine broken-reference failure rather than an improvement, and only the
 *    consumer knows the right name. Supply one at the call site:
 *
 *      <PopoverContent aria-label="Focal point" />
 *      // or, when a visible title is rendered:
 *      <PopoverContent aria-labelledby={titleId}>
 *        <PopoverTitle id={titleId}>Focal point</PopoverTitle>
 *
 * 2. It does not work around a defect in the pinned primitive's custom-anchor
 *    path. `PopoverAnchor` is measurably broken in `radix-ui@1.6.7` when the
 *    anchor is declared BEFORE the trigger: the panel is positioned against a
 *    detached node, reporting `--radix-popover-content-available-width` of 0px
 *    and pinning itself to the viewport origin — measured ~496px left and
 *    ~503px above its intended position, on top of the sticky header, silently
 *    and reproducibly from a clean load. Cause, read in the installed source:
 *    `PopperAnchor`'s callback ref ignores a null node
 *    (`if (node) onAnchorChange(node)`), so unmounting never clears the
 *    context anchor, while `PopoverAnchor` flips `hasCustomAnchor` from a
 *    mount effect and `PopoverTrigger` renders
 *    `hasCustomAnchor ? trigger : <Popper.Anchor asChild>{trigger}</…>`. Both
 *    anchors register on the first commit, React attaches refs in tree order
 *    so the later-declared one wins, and the trigger's implicit wrapper then
 *    unmounts leaving its detached node behind as the reference.
 *
 *    The workaround is ordering, and it is verified: declare
 *    `PopoverTrigger` BEFORE `PopoverAnchor` and positioning is correct, with
 *    0.000px scroll-tracking error. `asChild` makes no difference either way.
 *    This is not patched here because the fault is in the pinned dependency,
 *    §0.6.1 pins it exactly, and a remount hack inside a generated file would
 *    be invisible to the next upgrade. `FocalPointPicker` is the consumer this
 *    affects.
 *
 * The rest of the surface already resolves to tokens without a class change.
 * `bg-popover` and `text-popover-foreground` read `--popover` and
 * `--popover-foreground` through the `@theme inline` alias layer; the bare
 * `border` needs no colour utility because `@layer base` sets `border-color:
 * var(--color-border)` on every element, which is what points it at
 * `--border`; and `rounded-md` reads `--radius-md`. There is not one colour
 * literal in this file — `npm run audit:tokens` fails on a colour literal even
 * in a generated file, and that is the axis it is right to police.
 *
 * ONE LIGHT THEME (§0.3.3). No `dark:` variant is authored here. The site
 * ships a single light theme, the `.dark` block the registry emits is deleted
 * from `app/globals.css` by that file's owner, and `next-themes` is not a
 * dependency.
 *
 * COLLISION AWARENESS (§0.4.5) is a hard requirement, and the way to meet it
 * is to leave it alone. Radix flips and shifts the panel to keep it in view;
 * this file never passes `avoidCollisions={false}`, never pins
 * `collisionBoundary` and never sets a negative `collisionPadding`, so the
 * defaults hold and a caller may still tighten them. That is what keeps a
 * panel from opening underneath the sticky header, breadcrumb bar, edit
 * toolbar or mobile CTA bar — all of which sit inside
 * `env(safe-area-inset-*)` padding — or off the bottom of a 320px viewport,
 * where §0.4.5's keyboard sweep requires every focused element to be fully
 * visible.
 *
 * ACCESSIBILITY is inherited from the primitive and costs nothing visually:
 * Escape closes, focus returns to the trigger, focus is managed inside the
 * panel, and the trigger carries `aria-expanded` and `aria-controls`. None of
 * it has a legacy counterpart — the site being replaced has no popover,
 * tooltip or dropdown at all, `public/js/main.js` is 1,083 bytes with no key
 * handler anywhere, and `public/css/style.css` suppresses the focus ring
 * site-wide with `outline: none !important`. This is net-new surface measured
 * against WCAG 2.2 AA, not a port.
 */

"use client";

import * as React from "react";
import { Popover as PopoverPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

/**
 * The root. Uncontrolled by default; `open`, `defaultOpen`, `onOpenChange` and
 * `modal` all reach the primitive through the spread rather than being
 * enumerated, so the component's prop type stays exactly the primitive's and
 * cannot drift from it as `radix-ui` moves.
 */
function Popover({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Root>) {
  return <PopoverPrimitive.Root data-slot="popover" {...props} />;
}

/**
 * The trigger. Use `asChild` to project the state and ARIA wiring onto a
 * `Button` rather than nesting a control inside a control — the legacy site
 * nests a `<button>` inside an `<a href="/donate">`, which is invalid markup
 * producing two tab stops for one action.
 */
function PopoverTrigger({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Trigger>) {
  return <PopoverPrimitive.Trigger data-slot="popover-trigger" {...props} />;
}

/**
 * The positioned panel, portalled to the document body so no ancestor's
 * `overflow` or stacking context can clip it. The legacy site clips content
 * exactly this way: `#colorlib-page { overflow: hidden }` is what hides the
 * 76px of polaroid frame that renders off-screen at 390px.
 *
 * All four positioning props from §0.3.2 are exposed and forwarded:
 *
 *   - `align` and `sideOffset` are destructured to carry the registry's
 *     defaults (`"center"` and `4`), then passed explicitly. Because they are
 *     destructured out of `props`, the later spread cannot contain them and
 *     there is no order-dependent override to reason about — a caller's value
 *     replaces the default rather than fighting it.
 *   - `side` and `alignOffset` reach the primitive untouched through the
 *     spread. They are deliberately not re-declared: `React.ComponentProps<
 *     typeof PopoverPrimitive.Content>` already types all four, so the public
 *     type exposes them while this file adds no shadowing default. Renaming or
 *     dropping any of the four would break `date-picker.tsx` and
 *     `FocalPointPicker.tsx`.
 */
function PopoverContent({
  className,
  align = "center",
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Content>) {
  return (
    <PopoverPrimitive.Portal>
      <PopoverPrimitive.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(
          "z-(--z-dropdown) w-72 max-w-(--radix-popover-content-available-width) origin-(--radix-popover-content-transform-origin) rounded-md border bg-popover p-4 text-popover-foreground shadow-popover outline-hidden data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
          className,
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  );
}

/**
 * An explicit anchor, for the case the panel must position against something
 * other than its trigger — a crosshair on an image rather than the button that
 * opened it, which is `FocalPointPicker`'s shape.
 */
function PopoverAnchor({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Anchor>) {
  return <PopoverPrimitive.Anchor data-slot="popover-anchor" {...props} />;
}

/** Optional heading block inside the panel. Layout only, no role. */
function PopoverHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="popover-header"
      className={cn("flex flex-col gap-1 text-sm", className)}
      {...props}
    />
  );
}

/**
 * The panel's visible title. Rendered as a `div` while typed against `"h2"` —
 * that asymmetry is the pinned registry's own, kept verbatim rather than
 * "corrected", and it is defensible on both axes: a popover is not a dialog,
 * so it needs no accessible name derived from a heading, and emitting a real
 * `<h2>` here would inject an out-of-sequence heading into the page outline.
 * The legacy site demonstrates the cost of getting that wrong — an `<h3>`
 * after an `<h1>` with no `<h2>` anywhere, and four `<h1>` elements on the
 * home page.
 */
function PopoverTitle({ className, ...props }: React.ComponentProps<"h2">) {
  return (
    <div
      data-slot="popover-title"
      className={cn("font-medium", className)}
      {...props}
    />
  );
}

/** Supporting copy inside the panel, at `--muted-foreground`. */
function PopoverDescription({
  className,
  ...props
}: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="popover-description"
      className={cn("text-muted-foreground", className)}
      {...props}
    />
  );
}

export {
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverAnchor,
  PopoverHeader,
  PopoverTitle,
  PopoverDescription,
};
