"use client";

/**
 * Sheet — the edge-anchored overlay panel, built on the Radix Dialog
 * primitive.
 *
 * Generated by `shadcn add sheet` against the pinned CLI (`shadcn@4.19.0`) and
 * the committed `components.json`. Registry membership was verified before
 * generation per §0.3.1: `shadcn view sheet` resolves as `registry:ui` with
 * `radix-ui` as its sole declared dependency, which is already pinned at
 * 1.6.7, so no manifest change accompanied this file.
 *
 * WHY THIS FILE MATTERS BEYOND ITS SIZE
 *
 * Two surfaces in this application are sheets, and they sit at opposite ends
 * of the visual field:
 *
 *   - `side="left"` is the mobile navigation drawer (§0.3.2, "Mobile nav
 *     drawer"). It replaces the legacy nav toggle at
 *     `resources/views/layout.antlers.html:29`, whose entire attribute set was
 *     `href`, `class` and `style`. Measured against the source rather than
 *     assumed: its accessible name was the empty string (its only child was an
 *     empty `<i>`); `aria-expanded`, `aria-label`, `aria-controls` and `role`
 *     were all absent, and `aria-expanded` stayed absent *while the menu was
 *     open*, so the control never conveyed its own state; `public/js/main.js`
 *     is 51 lines and contains zero matches for `keydown`, `keyup`,
 *     `keypress`, `Escape` or `keyCode`, so Escape did nothing and focus never
 *     entered the panel; and the collapsed drawer sat at
 *     `transform: translateX(-270px)` while still visible, with neither
 *     `aria-hidden` nor `inert`, putting 13 reachable off-screen tab stops
 *     ahead of any on-screen content and reading the whole menu aloud to a
 *     screen reader.
 *
 *     Radix's Dialog foundation fixes every one of those by construction:
 *     `SheetTrigger` is a real `<button>` carrying `aria-expanded` and
 *     `aria-controls`, `SheetContent` is a labelled `role="dialog"`, focus
 *     moves into the panel on open and is trapped there, Escape closes, focus
 *     returns to the trigger on close, and the closed panel is unmounted
 *     outright so no tab sweep can enter it.
 *
 *     Note the mechanism, because it is not the one most readers assume:
 *     verified against the rendered DOM, `radix-ui@1.6.7` does NOT emit
 *     `aria-modal`. It establishes modality instead by setting
 *     `aria-hidden="true"` on every sibling of the portal and
 *     `pointer-events: none` on `<body>`, with the panel itself opted back in.
 *     That is the stronger guarantee here, and it is the exact inverse of the
 *     legacy defect: where the old markup left an off-screen panel exposed to
 *     assistive technology, this hides everything that is not the panel.
 *
 *     One legacy behaviour is deliberately NOT reproduced: `main.js:39-46`
 *     closed the drawer on any `window.scroll`. That is a defect, not a
 *     feature — it closes the panel out from under someone scrolling a long
 *     menu — and Radix's own dismissal paths (Escape, scrim click,
 *     `onInteractOutside`) are the correct replacements.
 *
 *   - `side="right"` is the globals editor panel (§0.3.2, "Globals editor
 *     panel"), which hosts `Tabs` with six tabs — Contact and Address, Social
 *     and Portal Links, Branding, Announcement Presentation, Analytics and
 *     Maintenance. A right-edge panel is chosen over the tabbed *modal* the
 *     reference implementation used precisely because it keeps the page
 *     visible behind it: the values being edited (the address, the phone
 *     number, the logo) are rendered on that page. The tab content belongs to
 *     `GlobalsSheet.tsx`; what this file owes it is a panel that scrolls
 *     correctly under a long form and keeps its header and footer reachable.
 *
 * A NOTE ON HOW THIS FILE IS COMMENTED — PLEASE PRESERVE IT
 *
 * These comments never quote a utility class the file does not actually use,
 * and that restraint is load-bearing rather than stylistic. Tailwind's source
 * scanner is plain text matching: it does not parse TypeScript and does not
 * skip comments, so a class name mentioned in prose is generated into the
 * production stylesheet exactly as if it had been applied to an element. An
 * earlier draft of this header named the eight replaced classes verbatim and
 * emitted 20 unused rules and 3,128 bytes of dead CSS as a result — among them
 * a hard-coded colour and an outline-suppressing rule, the two things this
 * project's token and focus contracts exist to keep out of the stylesheet.
 * Replaced classes are therefore described by what they did, not named. To
 * re-check after editing, compile `app/globals.css` through
 * `@tailwindcss/postcss` and diff the emitted selector set against a
 * comment-stripped copy of this file; the difference should be nothing.
 *
 * WHAT WAS CHANGED FROM THE REGISTRY OUTPUT, AND WHY
 *
 * §0.3.5 exempts unmodified registry internals from the arbitrary-value ban,
 * and that exemption is respected: the emitted sizing (`w-3/4`,
 * `sm:max-w-sm`, `gap-4`, `p-4`, `size-4`) is untouched. Every change below is
 * required by a named clause rather than preferred, and each is annotated at
 * its call site:
 *
 *   1. The scrim's hard-coded black at 50% opacity became `bg-foreground/50`.
 *      Colour is the one axis §0.3.5 does not exempt, so a literal fails
 *      `npm run audit:tokens` in generated files as well as authored ones —
 *      and the audit strips the opacity modifier before testing the utility,
 *      so a fractional suffix is no escape.
 *   2. One literal z-index of 50, shared by the scrim and the panel, became
 *      `z-(--z-overlay)` and `z-(--z-modal)` — two distinct levels, so
 *      stacking no longer depends on DOM order, and neither reaches
 *      `--z-edit` (80), which §0.3.3 reserves as the ceiling for edit chrome.
 *   3. The default large box-shadow became `shadow-(--shadow-modal)`.
 *   4. The registry's in-and-out easing and its split 300ms/500ms duration
 *      pair became `ease-(--ease-out)` and a single
 *      `duration-(--duration-base)`, the 240ms §0.3.3 specifies.
 *   5. A single neutral surface for every side became the side-keyed surfaces
 *      §0.3.3 assigns to the two named consumers.
 *   6. Safe-area padding and internal scrolling were added; the registry
 *      provides neither and §0.4.5 requires both.
 *   7. The close control's focus treatment — a 2px ring scoped to `:focus`,
 *      plus a utility that suppresses the focus indicator — was replaced by
 *      `focus-visible:` and the project's own global focus ring. Two reasons:
 *      `:focus` fires on mouse clicks where UI guidance asks for
 *      `:focus-visible`, and the suppressing utility emits
 *      `outline-style: none`, which `app/globals.css` forbids anywhere in this
 *      project with or without `!important`. That is not a preference — it is
 *      the precise defect being repaired, since `public/css/style.css` killed
 *      the indicator site-wide on `a:hover, a:focus` and `:focus-visible`
 *      appeared zero times across all six legacy stylesheets.
 *   8. The extra-small radius default became `rounded-sm`, the §0.3.3 radius
 *      contract being sm/md/lg/pill/full.
 *
 * TOKEN AND MOTION MECHANICS WORTH KNOWING BEFORE EDITING
 *
 * `--z-*`, `--size-*` and `--duration-*` are NOT Tailwind namespaces —
 * `app/globals.css` says so explicitly and warns that a `z-modal` or
 * `w-datechip` utility silently yields nothing at all rather than erroring.
 * They are consumed here in the `utility-(--token)` form, which both compiles
 * and is verified: the token audit resolves every such reference against the
 * declared set, so a typo fails the build instead of quietly rendering as a
 * default. `--ease-*` and `--container-*` *are* namespaces and need no such
 * form.
 *
 * The slide is a CSS *animation* rather than a transition, so it is worth
 * stating why a duration utility governs it at all. `tw-animate-css@1.4.0`
 * defines its enter animation as
 * `enter var(--tw-animation-duration, var(--tw-duration, .15s))
 * var(--tw-ease, ease) …`, and Tailwind's duration and easing utilities set
 * `--tw-duration` and `--tw-ease`. Verified in compiled output: the two
 * utilities below emit exactly those custom properties, so the tokens drive
 * the animation and not merely the transition shorthand beside them.
 *
 * Reduced motion is NOT handled in this file, and adding it here would be a
 * duplicate. `app/globals.css` carries an unlayered
 * `@media (prefers-reduced-motion: reduce)` block that collapses every
 * animation and transition to 1ms globally; being unlayered, it outranks the
 * utilities layer without `!important`, so nothing here can defeat it. It
 * collapses to 1ms rather than suppressing the animation outright on purpose —
 * Radix waits for `animationend` before unmounting, and an animation that
 * never runs never fires that event, which would leave the panel mounted
 * forever. For the same reason this file must never disable an animation.
 *
 * `border-l` and `border-r` below carry no colour utility because they need
 * none: `app/globals.css` sets `border-color: var(--color-border)` on `*` in
 * `@layer base`, so a bordered edge already draws in `--border` and restating
 * it would be a no-op duplicate.
 *
 * One light theme ships (§0.3.3, "Colour mode"), so no `dark:` variant is
 * authored anywhere in this file and `app/globals.css` carries no `.dark`
 * block.
 *
 * THE ACCESSIBLE NAME IS THE CONSUMER'S OBLIGATION
 *
 * `SheetTitle` is REQUIRED, not optional (§0.3.2). A dialog with no accessible
 * name is announced as an unlabelled region, Radix logs a runtime warning, and
 * `lighthouserc.json` asserts a Lighthouse accessibility score of exactly
 * 1.00. Where the design shows no visible heading — the mobile nav drawer, for
 * instance — hide it visually and keep it in the accessibility tree; never
 * omit it:
 *
 * ```tsx
 * <SheetContent side="left">
 *   <SheetHeader className="sr-only">
 *     <SheetTitle>Site navigation</SheetTitle>
 *     <SheetDescription>Browse the Cambridge-Ellis School website.</SheetDescription>
 *   </SheetHeader>
 *   <NavTree />
 * </SheetContent>
 * ```
 *
 * Radix also warns when `SheetContent` has no description. Supply
 * `SheetDescription`, or pass `aria-describedby={undefined}` on `SheetContent`
 * to state deliberately that there is none.
 *
 * @see nextjs/app/globals.css — the sole declaration site for every token read here
 */

import * as React from "react";
import { XIcon } from "lucide-react";
import { Dialog as SheetPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

/**
 * The root. Controlled with `open`/`onOpenChange`, uncontrolled with
 * `defaultOpen`. Renders no DOM of its own — it is the context provider that
 * couples the trigger to the panel.
 */
function Sheet({ ...props }: React.ComponentProps<typeof SheetPrimitive.Root>) {
  return <SheetPrimitive.Root data-slot="sheet" {...props} />;
}

/**
 * The control that opens the panel.
 *
 * This is the component that closes the largest single accessibility gap in
 * the migration. Radix renders a real `<button>` carrying
 * `aria-haspopup="dialog"` and `aria-expanded`, and it maintains
 * `aria-expanded` in BOTH states — `"false"` closed, `"true"` open — where the
 * legacy toggle never set it at all, in either state.
 *
 * `aria-controls` behaves differently and the distinction is worth recording,
 * because it is easy to assert wrongly in a test: it is emitted ONLY while the
 * panel is open, and is absent while closed. Verified in both jsdom and a real
 * browser. That is correct rather than a gap — the panel is unmounted when
 * closed, so a permanent `aria-controls` would be a dangling IDREF pointing at
 * no element. Do not "fix" it by hard-coding the attribute.
 *
 * Pass `asChild` to project those attributes onto your own element rather than
 * nesting a second interactive node inside it.
 */
function SheetTrigger({
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Trigger>) {
  return <SheetPrimitive.Trigger data-slot="sheet-trigger" {...props} />;
}

/**
 * Closes the panel. Use it for an explicit "Done" or "Cancel" affordance in
 * `SheetFooter`; Escape and a scrim click already close without it.
 */
function SheetClose({
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Close>) {
  return <SheetPrimitive.Close data-slot="sheet-close" {...props} />;
}

/**
 * Portals the panel to the document body.
 *
 * Deliberately not exported — `SheetContent` renders it. Escaping the page's
 * stacking and clipping contexts is what keeps a drawer from being cut off by
 * an ancestor, and the legacy layout is exactly why that matters:
 * `#colorlib-page` carried `overflow: hidden`, which silently clipped
 * overflowing children instead of revealing them.
 */
function SheetPortal({
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Portal>) {
  return <SheetPrimitive.Portal data-slot="sheet-portal" {...props} />;
}

/**
 * The scrim behind the panel. Not exported; `SheetContent` renders it.
 *
 * `bg-foreground/50` replaces the registry's hard-coded black: a CSS named
 * colour is a colour literal, and colour is the one axis §0.3.5 fails in
 * generated files as well as authored ones. `--foreground` is the brand's warm
 * dark ink, so the dim it produces belongs to this palette rather than being a
 * neutral black wash.
 *
 * It sits at `--z-overlay` (50), one level below the panel's `--z-modal` (60),
 * so the two cannot depend on DOM order to stack correctly.
 */
function SheetOverlay({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Overlay>) {
  return (
    <SheetPrimitive.Overlay
      data-slot="sheet-overlay"
      className={cn(
        "fixed inset-0 z-(--z-overlay) bg-foreground/50 duration-(--duration-base) ease-(--ease-out) data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:animate-in data-[state=open]:fade-in-0",
        className,
      )}
      {...props}
    />
  );
}

/**
 * The panel itself: a labelled `role="dialog"` with `tabindex="-1"`, focus
 * trapped while open, unmounted while closed, and modality supplied by the
 * sibling `aria-hidden` mechanism described in the file header rather than by
 * an `aria-modal` attribute.
 *
 * `side` SELECTS WHICH EDGE THE PANEL SLIDES FROM. It is not a positioner
 * hint, and the difference is worth stating because the neighbouring
 * primitives spell it identically for a different job: `PopoverContent`,
 * `TooltipContent` and `DropdownMenuContent` take `side` as a hint *relative
 * to a trigger*, alongside `align`, `sideOffset` and `alignOffset`, while
 * `DialogContent` takes none of them and is centred. §0.3.2 separates those
 * rows for exactly this reason. `SheetContent` therefore exposes `side` and
 * NOTHING else from that family — no `align`, no `sideOffset`, no
 * `alignOffset`.
 *
 * SURFACES ARE KEYED TO THE SIDE, because the two sides are two different
 * components in the design (§0.3.3). `side="left"` is the navigation drawer
 * and takes `--sidebar` / `--sidebar-foreground`; `side="right"` is the
 * globals editor panel and takes `--popover` / `--popover-foreground`. `top`
 * and `bottom` have no named consumer and keep the neutral `--background`
 * from the base classes, which `cn` resolves in favour of whichever surface
 * the side branch supplies.
 *
 * SCROLLING. `overflow-auto overscroll-contain` is added because the registry
 * provides neither, and §0.4.5 requires a panel with more content than
 * viewport height to "scroll internally without the page behind it scrolling".
 * Radix already locks body scroll; `overscroll-contain` is what additionally
 * stops a touch fling at the end of the panel from chaining to the page. The
 * all-axis form is chosen over a single-axis one so a consumer needing pinned
 * chrome — the six-tab globals panel, which scrolls its own tab body — can
 * override it from `className`: `tailwind-merge` treats all-axis and
 * single-axis overflow as separate groups, so a single-axis default would
 * survive the merge and the two would then fight in the cascade.
 *
 * `top` and `bottom` additionally take `max-h-dvh`. Without it `h-auto` leaves
 * no constrained height for overflow to act against, and tall content simply
 * runs off-screen instead of scrolling. `left` and `right` need no equivalent
 * because `inset-y-0` with `h-full` already bounds them to the viewport.
 *
 * SAFE AREA. The `chrome-safe-*` utilities from `app/globals.css` apply
 * `env(safe-area-inset-*, 0px)` per side, so a full-height drawer's content
 * clears a notch and a home indicator (§0.4.5). They are applied to
 * `SheetContent`, which carries no padding of its own — the registry puts
 * padding on `SheetHeader`/`SheetFooter` — so there is no same-axis collision.
 * A consumer that overrides padding on this element, as the sidebar's mobile
 * variant does, takes ownership of its own insets; that is the documented
 * contract, not an oversight.
 *
 * INITIAL FOCUS IS SET DELIBERATELY, and it is the one behavioural override in
 * this file. Left to itself, the primitive moves focus to the first tabbable
 * candidate it finds inside the panel — measured, in both jsdom and a real
 * browser, as the footer's close control rather than the first navigation link.
 * In a panel taller than the viewport that control sits BELOW the visible area
 * (measured at y=950 inside a 900px-tall panel) and the primitive focuses it
 * with `preventScroll`, so it is never revealed. A keyboard user would open the
 * drawer and receive focus on something they cannot see, which fails WCAG 2.2
 * SC 2.4.11 Focus Not Obscured at the Level AA this project targets (§0.4.5).
 *
 * The panel container is therefore focused instead. That is the WAI-ARIA dialog
 * pattern's own first option and it is strictly better here: the screen reader
 * announces the dialog's role and its `SheetTitle` name, the panel stays at
 * `scrollTop: 0` so the header is what a sighted user sees, and the first Tab
 * then enters the content in document order. The container is focusable because
 * the primitive gives it `tabindex="-1"`.
 *
 * A consumer keeps full control: pass your own `onOpenAutoFocus` and it runs
 * first, and if it calls `preventDefault()` this default stands aside entirely.
 *
 * @param side Which edge the panel slides from. Defaults to `"right"`.
 * @param showCloseButton Renders the built-in close control. Set `false` when
 *   the consumer supplies its own.
 * @param onOpenAutoFocus Optional override for the initial-focus behaviour
 *   described above.
 */
function SheetContent({
  className,
  children,
  side = "right",
  showCloseButton = true,
  onOpenAutoFocus,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Content> & {
  side?: "top" | "right" | "bottom" | "left";
  showCloseButton?: boolean;
}) {
  /**
   * Focus the panel itself unless the consumer has already handled it.
   *
   * The primitive dispatches this as a cancelable event on the panel element,
   * so `currentTarget` is the panel while the handler runs. Calling
   * `preventDefault` suppresses the primitive's own candidate search, and
   * because the primitive runs a consumer handler ahead of its own and skips
   * its own once the default is prevented, this becomes the single decider.
   */
  const handleOpenAutoFocus = React.useCallback(
    (event: Event) => {
      onOpenAutoFocus?.(event);
      if (event.defaultPrevented) return;
      event.preventDefault();
      const panel = event.currentTarget;
      if (panel instanceof HTMLElement) {
        panel.focus({ preventScroll: true });
      }
    },
    [onOpenAutoFocus],
  );

  return (
    <SheetPortal>
      <SheetOverlay />
      <SheetPrimitive.Content
        data-slot="sheet-content"
        onOpenAutoFocus={handleOpenAutoFocus}
        className={cn(
          "fixed z-(--z-modal) flex flex-col gap-4 overflow-auto overscroll-contain bg-background shadow-(--shadow-modal) transition duration-(--duration-base) ease-(--ease-out) data-[state=closed]:animate-out data-[state=open]:animate-in",
          side === "right" &&
            "inset-y-0 right-0 h-full w-3/4 border-l bg-popover chrome-safe-inline chrome-safe-top chrome-safe-bottom text-popover-foreground data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm",
          side === "left" &&
            "inset-y-0 left-0 h-full w-3/4 border-r bg-sidebar chrome-safe-inline chrome-safe-top chrome-safe-bottom text-sidebar-foreground data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left sm:max-w-sm",
          side === "top" &&
            "inset-x-0 top-0 h-auto max-h-dvh border-b chrome-safe-inline chrome-safe-top data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top",
          side === "bottom" &&
            "inset-x-0 bottom-0 h-auto max-h-dvh border-t chrome-safe-inline chrome-safe-bottom data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
          className,
        )}
        {...props}
      >
        {children}
        {showCloseButton && (
          /*
           * The close control stays a DIRECT CHILD of the content element, and
           * that is load-bearing rather than incidental: the registry's own
           * sidebar hides this control with a direct-child `button` variant,
           * so wrapping it in a positioning element would silently break that
           * consumer.
           *
           * Which is why the safe-area inset is folded into this element's own
           * offsets instead of being inherited. An absolutely positioned box
           * is laid out against its containing block's PADDING box, so the
           * `chrome-safe-top` padding on `SheetContent` above does not move it
           * — a plain 1rem offset would still measure from the panel's border
           * edge and put the control under a notch. The physical
           * `right`/`safe-area-inset-right` pairing is deliberate too: `env()`
           * has no logical form, so pairing a logical inline offset with a
           * physical inset would reverse under RTL. Everything here is
           * physical because `side` itself is physical.
           *
           * The target is 44px on touch and 32px from `sm` upward, matching
           * the control sizes in §0.4.5's responsive matrix and clearing the
           * WCAG 2.2 SC 2.5.8 minimum at both. The icon stays at the
           * registry's `size-4` inside the enlarged hit area, which is what
           * `inline-flex items-center justify-center` is for.
           *
           * Focus is left to the global `:focus-visible` ring in
           * `app/globals.css` for the reasons in item 7 of the header.
           * `focus-visible:opacity-100` is added so a keyboard user gets the
           * same full-strength icon that a hover gives — Tailwind's `hover:`
           * variant already carries its own `@media (hover: hover)`, so a
           * hover state cannot latch on a touch device.
           *
           * `data-[state=open]:bg-secondary` is unmodified registry output and
           * is inert — Radix's `Dialog.Close` sets no `data-state` — so it is
           * kept rather than pruned, per §0.3.5's exemption for generated
           * internals. `secondary` is a declared token, so it costs the audit
           * nothing.
           */
          <SheetPrimitive.Close className="absolute top-[calc(--spacing(4)_+_env(safe-area-inset-top,0px))] right-[calc(--spacing(4)_+_env(safe-area-inset-right,0px))] inline-flex size-(--size-control-touch) items-center justify-center rounded-sm opacity-70 transition-opacity duration-(--duration-base) ease-(--ease-out) hover:opacity-100 focus-visible:opacity-100 disabled:pointer-events-none data-[state=open]:bg-secondary sm:size-(--size-control)">
            <XIcon className="size-4" />
            <span className="sr-only">Close</span>
          </SheetPrimitive.Close>
        )}
      </SheetPrimitive.Content>
    </SheetPortal>
  );
}

/**
 * The panel's heading region. Host `SheetTitle` here, and `SheetDescription`
 * alongside it.
 *
 * Add `className="sr-only"` where the design shows no visible heading — that
 * keeps the accessible name in the tree at zero visual cost, which is the
 * whole point of the pattern.
 */
function SheetHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-header"
      className={cn("flex flex-col gap-1.5 p-4", className)}
      {...props}
    />
  );
}

/**
 * The panel's action region. `mt-auto` pushes it to the far edge of the flex
 * column, so it sits at the bottom of a short panel and after the content of a
 * tall one.
 */
function SheetFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-footer"
      className={cn("mt-auto flex flex-col gap-2 p-4", className)}
      {...props}
    />
  );
}

/**
 * The panel's accessible name, wired to `aria-labelledby` by Radix.
 *
 * REQUIRED on every sheet (§0.3.2). Omitting it produces an unlabelled dialog,
 * a Radix runtime warning and a Lighthouse accessibility regression against a
 * gate asserting exactly 1.00. Hide it with `sr-only` rather than dropping it.
 */
function SheetTitle({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Title>) {
  return (
    <SheetPrimitive.Title
      data-slot="sheet-title"
      className={cn("font-semibold text-foreground", className)}
      {...props}
    />
  );
}

/**
 * The panel's accessible description, wired to `aria-describedby` by Radix.
 *
 * Radix warns when a dialog has neither this nor an explicit
 * `aria-describedby={undefined}` on `SheetContent`, so state the absence
 * deliberately if there genuinely is no description.
 */
function SheetDescription({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Description>) {
  return (
    <SheetPrimitive.Description
      data-slot="sheet-description"
      className={cn("text-sm text-muted-foreground", className)}
      {...props}
    />
  );
}

/*
 * The eight parts §0.3.2 specifies, and only those. `SheetPortal` and
 * `SheetOverlay` are intentionally internal: `SheetContent` renders both, and
 * exporting them would invite a consumer to assemble a panel with a mismatched
 * scrim or none at all.
 */
export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
};
