"use client";

/**
 * Tooltip — the anchored, supplementary label for an icon-only control.
 *
 * ## Provenance
 *
 * One of the 38 registry-generated files in `components/ui/`. Membership was
 * verified against the pinned CLI before generation, as §0.3.1 requires:
 * `shadcn@4.19.0 view tooltip` resolves and reports exactly one dependency,
 * `radix-ui`, which `package.json` already pins exact at 1.6.7 — so generation
 * added no dependency and loosened no pin. The file was then emitted by
 * `shadcn add tooltip` against the committed `components.json`
 * (`style: new-york`, `rsc: true`, `baseColor: stone`).
 *
 * Registry output is project source here and is reviewed like any other file,
 * which is why `components/ui/**` is deliberately not ignored by
 * `eslint.config.mjs`. Three token corrections were applied on top of the
 * generated bytes and are listed under "Token corrections" below. A future
 * `shadcn add tooltip` will overwrite this file and silently revert all three;
 * re-apply them, and re-read that section rather than trusting the diff to be
 * self-explanatory.
 *
 * ## Nothing here is a port
 *
 * The legacy Statamic site had no tooltip at all: `public/css/ces.css` contains
 * zero occurrences of `tooltip`, and zero `title` attributes appear in it. This
 * component is entirely net-new, and its job is narrow — labelling the edit
 * affordances that make per-field editing legible. §0.3.2 assigns it to "the
 * field pencil and confirm/cancel controls", i.e. the pencil, check and X in
 * `components/cms/FieldFrame.tsx`.
 *
 * ## A TooltipProvider ancestor is REQUIRED, and this file does not mount one
 *
 * Radix creates the provider context with no default value, so `Tooltip`,
 * `TooltipTrigger` and `TooltipContent` each throw at render without a
 * `TooltipProvider` above them — the message is
 * `` `Tooltip` must be used within `TooltipProvider` ``. This is a hard runtime
 * error, not a degraded tooltip.
 *
 * The mount belongs to a consuming layout, not to this module: a provider
 * rendered per tooltip would defeat `skipDelayDuration`, which exists so that
 * moving between neighbouring triggers — the pencil, then the check, then the X
 * — does not re-incur the open delay on each one. Mount it once around the
 * subtree that owns the controls, and prefer the narrowest such subtree: the
 * editor providers mount only on a verified-authenticated request, so a public
 * anonymous response should carry no tooltip machinery at all.
 *
 * ## A TOOLTIP IS SUPPLEMENTARY AND NEVER THE SOLE ACCESSIBLE NAME
 *
 * §0.3.2's phrasing — these controls "use `Tooltip` for their labels" — must
 * not be read as *the tooltip is the label*. Every icon-only trigger keeps its
 * own `aria-label`, or visually-hidden text, IN ADDITION to its tooltip:
 *
 *   - A tooltip is unreachable by touch. There is no hover on a phone, and
 *     §0.4.5's responsive matrix puts the confirm/cancel pair at 44 x 44 px
 *     specifically for touch at 320–575 px. A control whose only name is a
 *     hover affordance is nameless for exactly those visitors.
 *   - The measured baseline is what this rule is guarding against. The legacy
 *     nav toggle's entire attribute set is `href`, `class`, `style`; its
 *     accessible name is the empty string, and Lighthouse fails `link-name`
 *     three times over — the toggle plus both icon-only social links.
 *   - `lighthouserc.json` asserts an accessibility score of 1.00 exactly, so a
 *     single nameless control fails the build.
 *
 * `TooltipContent` therefore renders `role="tooltip"` content that is announced
 * as a description, and the name still has to come from the trigger. Where the
 * tooltip text and the accessible name would be identical, that duplication is
 * correct and intended.
 *
 * ## Keyboard behaviour is Radix's, and must not be suppressed
 *
 * Focusing the trigger opens the tooltip (not hover alone), and Escape
 * dismisses it while leaving focus on the trigger. Both come from
 * `TooltipPrimitive`; do not intercept `onEscapeKeyDown` or replace the trigger
 * with a non-focusable element.
 *
 * ## Token corrections applied to the generated output
 *
 * Each resolves a value the registry hardcodes to the §0.3.3 contract. Generated
 * arbitrary SIZING values are deliberately left alone — §0.3.5 scopes the
 * zero-hardcoded-values rule to authored code precisely so that pinning the
 * registry stays worthwhile — but the colour axis fails even in generated files,
 * and `audit:tokens` enforces that asymmetry.
 *
 * A NOTE ON HOW THE THREE ARE WORDED. Each names the TOKENS involved rather
 * than spelling out the utility class the registry shipped. That is deliberate,
 * because Tailwind 4's automatic source detection scans THIS FILE: a utility
 * name written in a comment is extracted as a candidate and can be emitted as a
 * real rule. The consequence is not hypothetical in this repository —
 * `scripts/audit-tokens.mjs` mentions an arbitrary background utility in its own
 * prose, and the compiler emits it with an unresolvable `url()` that fails a
 * Turbopack build outright. Naming the token is both more precise, §0.3.3 being
 * a token contract, and immune to that. Keep it that way when editing these
 * comments.
 *
 *   1. SURFACE. The registry surfaces the chip on the `--foreground` colour
 *      with `--background` text, and fills the arrow from `--foreground` too:
 *      an inverted dark chip. §0.3.2 groups tooltip with popover and
 *      dropdown-menu, and §0.3.3 provides `--shadow-popover` in its Elevation
 *      group for exactly these anchored overlays, so the surface resolves to
 *      `--popover`, `--popover-foreground` and `--shadow-popover`. This is
 *      design-system alignment rather than a contrast repair: the registry pair
 *      is the same two values inverted and measures 10.33:1, and the popover
 *      pair was MEASURED in Chrome at 10.78:1 — #ffffff surface against
 *      #374035 text, which is the legacy `$body` colour exactly — clearing AA
 *      (4.5:1) and AAA (7:1). Nothing is given up.
 *
 *      No border is applied, and the trade is recorded rather than hidden.
 *      Measured, the surface sits at 1.04:1 against the #fafafa page, so the
 *      chip's BOUNDARY rests entirely on the 10%-opacity shadow and the edge
 *      is genuinely soft. That is not a WCAG failure — SC 1.4.11 governs the
 *      boundary of a user-interface COMPONENT, and a tooltip is a description
 *      rather than a control, while its text contrast is 10.78:1 — and
 *      `--border` is not an available remedy: `globals.css` carries a standing
 *      BLITZY [A11Y] flag recording that this warm scale cannot reach 3:1
 *      against a 98.5%-lightness ground, so a stroke would take the boundary
 *      from 1.04:1 to roughly 1.2:1 while adding a seam the arrow would then
 *      have to break. Elevation is therefore the deliberate distinguisher. A
 *      designer wanting a harder edge needs a new token, not an edit here.
 *
 *   2. LAYERING. The registry's literal z-index of 50 becomes
 *      `z-(--z-dropdown)` (40), which sits below
 *      `--z-overlay`, `--z-modal` and `--z-toast`, and well below `--z-edit`
 *      (80) so the edit chrome always wins. The arbitrary-property form is
 *      mandatory, not stylistic: Tailwind 4 has no `--z-*` namespace, so a bare
 *      `z-dropdown` emits nothing at all and nothing errors.
 *
 *   3. MOTION. The registry ships the enter and exit keyframes with no duration
 *      or easing, falling back to tw-animate-css's `.15s ease`. They are pinned
 *      to `duration-(--duration-fast)` (120ms — a tooltip fade is a
 *      micro-interaction, so fast rather than base) and `ease-out`, which
 *      resolves to the CES `cubic-bezier(.22, 1, .36, 1)` because `--ease-*`
 *      IS a Tailwind namespace and `globals.css` redeclares it. As with `--z-*`,
 *      `--duration-*` is NOT a namespace, hence the arbitrary-property form.
 *
 *      Reduced motion needs nothing here. The unlayered block at the end of
 *      `globals.css` collapses animation and transition durations to 1ms under
 *      `prefers-reduced-motion: reduce`, unlayered so it outranks Tailwind's
 *      utilities without `!important` — a `duration-*` on this component cannot
 *      defeat it. It collapses to 1ms rather than `none` deliberately, because
 *      Radix waits for `animationend` before unmounting and `animation: none`
 *      never fires that event. The tooltip therefore still opens, still
 *      announces and still dismisses with the motion removed. Against a legacy
 *      baseline of zero `prefers-reduced-motion` rules in any authored
 *      stylesheet, that is the whole of the fix.
 *
 * One light theme ships (§0.3.3), so no `dark:` variant is authored here.
 *
 * @example
 * The provider is mounted once, by the layout that owns these controls.
 * `aria-label` on the button is the accessible NAME; the tooltip text is only
 * its visible echo, and the icon is hidden from assistive technology because
 * the button it sits inside is already named.
 *
 * ```tsx
 * <TooltipProvider>
 *   <Tooltip>
 *     <TooltipTrigger asChild>
 *       <Button size="icon" variant="ghost" aria-label="Edit this field">
 *         <Pencil aria-hidden="true" />
 *       </Button>
 *     </TooltipTrigger>
 *     <TooltipContent side="top" align="center" sideOffset={6}>
 *       Edit this field
 *     </TooltipContent>
 *   </Tooltip>
 * </TooltipProvider>
 * ```
 */

import * as React from "react";
import { Tooltip as TooltipPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

/**
 * Shares open/close timing across every tooltip in its subtree. REQUIRED — see
 * the module docblock; without it the parts below throw rather than degrade.
 *
 * `delayDuration` defaults to 0 (Radix's own default is 700ms), which the
 * registry chose and this project keeps: an editor hovering a pencil wants the
 * label now, and a 700ms wait on a control whose meaning is not yet learned
 * reads as an unresponsive interface. `skipDelayDuration` (300ms) and
 * `disableHoverableContent` are unchanged and forward through `...props`.
 *
 * @param props Radix `Tooltip.Provider` props. `delayDuration` overrides the
 *   0ms default; every other prop passes straight through.
 */
function TooltipProvider({
  delayDuration = 0,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Provider>) {
  return (
    <TooltipPrimitive.Provider
      data-slot="tooltip-provider"
      delayDuration={delayDuration}
      {...props}
    />
  );
}

/**
 * One tooltip: pairs a trigger with its content and owns the open state.
 *
 * Uncontrolled by default. Pass `open` with `onOpenChange` to control it, or
 * `defaultOpen` to start open — useful for a first-run hint, though never as a
 * substitute for a label.
 *
 * @param props Radix `Tooltip.Root` props — `open`, `defaultOpen`,
 *   `onOpenChange`, `delayDuration`, `disableHoverableContent`.
 */
function Tooltip({
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Root>) {
  return <TooltipPrimitive.Root data-slot="tooltip" {...props} />;
}

/**
 * The element the tooltip is anchored to and described by.
 *
 * Renders a `button` by default. Use `asChild` to project the behaviour onto
 * your own control — the near-universal case here, since the triggers are
 * `Button` instances carrying `lucide-react` icons. Whatever it wraps must be
 * focusable and must carry its own accessible name; the module docblock explains
 * why that is not negotiable.
 *
 * @param props Radix `Tooltip.Trigger` props, including `asChild`.
 */
function TooltipTrigger({
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Trigger>) {
  return <TooltipPrimitive.Trigger data-slot="tooltip-trigger" {...props} />;
}

/**
 * The positioned tooltip surface, portalled out of the trigger's DOM position
 * so an ancestor's `overflow: hidden` cannot clip it.
 *
 * POSITIONING PROPS FORWARD. `side`, `align`, `sideOffset`, `alignOffset`,
 * `avoidCollisions`, `collisionBoundary`, `collisionPadding` and `arrowPadding`
 * all reach Radix's positioner through `...props`. §0.3.2 groups tooltip with
 * popover and dropdown-menu for precisely this reason: these three are the
 * components that HAVE positioning props, whereas `DialogContent` exposes none
 * and is centered. Do not reach for `side` on a dialog by analogy with this.
 *
 * `sideOffset` defaults to 0, as the registry emits it. Note that 0 does not
 * mean flush: Radix's positioner adds the measured arrow height to the main-axis
 * offset whenever an arrow child is present, so the observed gap is
 * `sideOffset + 10px`. Measured — the default renders a 10px gap, and
 * `sideOffset={12}` renders 21.81px.
 *
 * ONE NOTE FOR TEST AUTHORS. Closing on pointer-leave needs TWO `pointermove`
 * events under synthetic input. Radix runs with hoverable content by default,
 * and it installs the document-level `pointermove` listener that closes the
 * tooltip only after processing the trigger's `pointerleave` — so the very move
 * that caused the leave cannot be the one evaluated. A real mouse emits a
 * continuous stream and never notices; a single CDP mouse jump leaves the
 * tooltip open and reads as a false failure. Keyboard focus and Escape have no
 * such quirk.
 *
 * @param className Merged through `cn`, so a caller's utility wins over the
 *   base classes rather than both being emitted and the winner decided by
 *   stylesheet order.
 * @param sideOffset Distance in px from the trigger. Defaults to 0.
 * @param children The label text. Keep it short; it echoes the trigger's
 *   accessible name rather than replacing it.
 * @param props Remaining Radix `Tooltip.Content` props, including every
 *   positioning prop above and `onEscapeKeyDown`.
 */
function TooltipContent({
  className,
  sideOffset = 0,
  children,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Content>) {
  return (
    <TooltipPrimitive.Portal>
      <TooltipPrimitive.Content
        data-slot="tooltip-content"
        sideOffset={sideOffset}
        className={cn(
          "z-(--z-dropdown) w-fit origin-(--radix-tooltip-content-transform-origin) animate-in rounded-md bg-popover px-3 py-1.5 text-xs text-balance text-popover-foreground shadow-popover duration-(--duration-fast) ease-out fade-in-0 zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95",
          className,
        )}
        {...props}
      >
        {children}
        <TooltipPrimitive.Arrow className="z-(--z-dropdown) size-2.5 translate-y-[calc(-50%_-_2px)] rotate-45 rounded-[2px] bg-popover fill-popover" />
      </TooltipPrimitive.Content>
    </TooltipPrimitive.Portal>
  );
}

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };
