title: Day
updated_by: 1179db75-8eeb-4bad-8e60-d5005aef7ef8
updated_at: 1635262873
blueprint: programs
description: |-
  The Cambridge-Ellis Day Program runs Monday through Friday, from 8:30 a.m. until 3:00 p.m. (with an option for daily dismissal at noon). We serve toddlers and preschool age children in seven classrooms that are grouped according to development.

  The curriculum at Cambridge-Ellis School is designed to promote social and emotional, cognitive, and pre-literacy skills and to provide a foundation for the study of mathematics and science. We have great respect for children as thinkers and learners and value their contributions to joint investigations. We believe that children learn best through play, active participation and engagement with teachers, peers, and materials.
main_image: Xbabies.jpg
