title: Enrichment
updated_by: 1179db75-8eeb-4bad-8e60-d5005aef7ef8
updated_at: 1635263073
blueprint: programs
description: |-
  Arts Adventure
  ​​Arts Adventure connects children to their world through artistic expression. Students participate in music, visual arts, dance and movement, drama, and literature, weekly for 30 - 45 minutes. Arts Adventure is designed to extend upon both classroom and Artisan Program themes, as well as provide Language Program students experiences in their cultural arts.

  Music Education
  Twice each month, children develop their musical roots and celebrate the international language of music with our specialist, Anna Laufenberg. Through songs and creative movement Anna introduces students to beats, rhythms, and scales. She delights and inspires children with her array of musical instruments from flute to contrabase. 

  Nature Program
  A hidden gem in the heart of Cambridge, our playgrounds inspire endless opportunities for adventure. Digging moats, climbing trees, transporting logs, cooking in mud kitchens, and observing chickens are part of our daily outdoor experiences. Weekly neighborhood walks to community green spaces and regularly scheduled visits from Habitat Wildlife Sanctuary further inspire awe and wonder as children learn about their world through discovery.

  Ann Murphy Artisan Program
  The Ann Murphy Artisan Program celebrates the artistic process, from imagination to creation. An endowment from the late Ann Murphy, beloved CES teacher and administrator, supports artist residencies for the children, professional development for our teachers and theme inspired family events.